// <auto-generated />
using FirstBank.Core.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstBank.Core.Migrations
{
    [DbContext(typeof(CustomerContext))]
    partial class CustomerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirstBank.Core.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IndustryId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = "1234567890",
                            IndustryId = 1,
                            Name = "Manufacturer A"
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = "2345678901",
                            IndustryId = 2,
                            Name = "School B"
                        },
                        new
                        {
                            Id = 3,
                            AccountNumber = "3456789012",
                            IndustryId = 3,
                            Name = "Telecom C"
                        });
                });

            modelBuilder.Entity("FirstBank.Core.Domain.Entities.Industry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Industries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Telecom"
                        });
                });

            modelBuilder.Entity("FirstBank.Core.Domain.Entities.RequiredField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IndustryId");

                    b.ToTable("RequiredFields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FieldName = "Invoice Number",
                            IndustryId = 1
                        },
                        new
                        {
                            Id = 2,
                            FieldName = "Quantity",
                            IndustryId = 1
                        },
                        new
                        {
                            Id = 3,
                            FieldName = "Delivery Address",
                            IndustryId = 1
                        },
                        new
                        {
                            Id = 4,
                            FieldName = "Matric Number",
                            IndustryId = 2
                        },
                        new
                        {
                            Id = 5,
                            FieldName = "Level",
                            IndustryId = 2
                        },
                        new
                        {
                            Id = 6,
                            FieldName = "Course",
                            IndustryId = 2
                        },
                        new
                        {
                            Id = 7,
                            FieldName = "GSM Number",
                            IndustryId = 3
                        },
                        new
                        {
                            Id = 8,
                            FieldName = "Network",
                            IndustryId = 3
                        },
                        new
                        {
                            Id = 9,
                            FieldName = "Residential Address",
                            IndustryId = 3
                        });
                });

            modelBuilder.Entity("FirstBank.Core.Domain.Entities.Customer", b =>
                {
                    b.HasOne("FirstBank.Core.Domain.Entities.Industry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("FirstBank.Core.Domain.Entities.RequiredField", b =>
                {
                    b.HasOne("FirstBank.Core.Domain.Entities.Industry", "Industry")
                        .WithMany("RequiredFields")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("FirstBank.Core.Domain.Entities.Industry", b =>
                {
                    b.Navigation("RequiredFields");
                });
#pragma warning restore 612, 618
        }
    }
}
